Issue 16
Mounayer/OptimizeIt pull request #17
Opened 2024-09-29 23:14 UTC by cleobnvntra

# Description

- Added the feature to use TOML "dotfile" as a config file.
- Modified `argHandler()` to accept an object `configOptions` which contains the parsed options from the TOML file.
- Each arg handler now uses the provided option value from the config file, but will prioritize command line arguments if provided.

# Checklist

- [x] Build does not fail.
- [x] Tested locally.
- [x] Linting errors if any are resolved.

# Testing Instructions

## Steps

### 1. Create a .options.toml file

### 2. Provide desired flag options. Option names are based on flag names used. Use -h or --help for assistance.
```
temperature = 0.8
output = ["file1.cpp", "file2.cpp"]
markdown = true
html = true
```

### 3. Run the tool with the desired file(s) to be optimized with the provided options.

2024-09-30 01:19 UTC, Mounayer approved these changes
praise: LGTM!! well done, it works great, just a couple of minor issues, and some suggestions and then it's good to go!!! 🔥

2024-09-30 01:19 UTC, Mounayer commented on .options.toml
> +break = asd
suggestion: I think it's better for the filename to be `.optimizeit-config.toml`, also, do you think it would be good to show what kinds of `options` this file would accept? i.e.: list all the options that work, in the file itself. You can comment them if you want, just so the user knows that that is an option!

2024-09-30 01:19 UTC, Mounayer commented on src/args/flag_handlers/apiKey.ts
>   * @returns { string } The API key.
suggestion: comments should be updated to reflect the newly added arg

2024-09-30 01:19 UTC, Mounayer commented on src/args/flag_handlers/html.ts
>   * @returns { boolean } True if html flag is provided, false otherwise.
suggestion: comments should be updated to reflect the newly added arg

2024-09-30 01:19 UTC, Mounayer commented on src/args/flag_handlers/markdown.ts
>   * @returns { boolean } True if markdown flag is provided, false otherwise.
suggestion: comments should be updated to reflect the newly added arg

2024-09-30 01:19 UTC, Mounayer commented on src/args/flag_handlers/model.ts
>   * @returns { string } The model name.
suggestion: comments should be updated to reflect the newly added arg

2024-09-30 01:19 UTC, Mounayer commented on src/args/flag_handlers/output.ts
>   * @returns  { OutputFlagPayload } The output flag and output files.
suggestion: comments should be updated to reflect the newly added arg

2024-09-30 01:19 UTC, Mounayer commented on src/args/flag_handlers/output.ts
> +  const outputFiles: string[] = outputConfig || []; // Initialize as an empty array
issue: Providing extra output files if the `TOML` config provided some, does not override it, but rather appended. 

If any output files are provided in the `CLI`, the entire `TOML` configuration regarding output files should be ignored!

2024-09-30 01:19 UTC, Mounayer commented on src/args/flag_handlers/temperature.ts
>   * @returns { number } The temperature value.
suggestion: comments should be updated to reflect the newly added arg

2024-09-30 01:19 UTC, Mounayer commented on src/toml_parser/index.ts
> + * @param config - The TOML configuration.
suggestion (none-blocking): This function doesn't have a parameter, is this a typo?

2024-09-30 01:19 UTC, Mounayer commented on src/toml_parser/index.ts
> +    const configFile = path.resolve('.options.toml');
issue: According to the instructions, the `TOML` that is processed must always be in the `~` home directory, no where else!

As in, if the user ever wanted to use this feature, they'd have a `.optimizeit-config.toml` file in their `~` home directory. Which this function would then check!

2024-10-01 23:01 UTC, cleobnvntra commented on .options.toml
> +break = asd
Done.

Changes:
- Changed the filename to look for `.optimizeit-config.toml` instead.
- Moved a sample `.optimizeit-config.toml` file under examples directory.
- Added a list of supported options in`.optimizeit-config.toml` which contains:
  - option name
  - short description of option
  - value type required
  - sample usage

2024-10-01 23:03 UTC, cleobnvntra commented on src/args/flag_handlers/html.ts
>   * @returns { boolean } True if html flag is provided, false otherwise.
Done.

2024-10-01 23:03 UTC, cleobnvntra commented on src/args/flag_handlers/model.ts
>   * @returns { string } The model name.
Done.

2024-10-01 23:03 UTC, cleobnvntra commented on src/args/flag_handlers/temperature.ts
>   * @returns { number } The temperature value.
Done.

2024-10-01 23:04 UTC, cleobnvntra commented on src/args/flag_handlers/apiKey.ts
>   * @returns { string } The API key.
Done.

2024-10-01 23:04 UTC, cleobnvntra commented on src/args/flag_handlers/markdown.ts
>   * @returns { boolean } True if markdown flag is provided, false otherwise.
Done.

2024-10-01 23:04 UTC, cleobnvntra commented on src/args/flag_handlers/output.ts
>   * @returns  { OutputFlagPayload } The output flag and output files.
Done.

2024-10-01 23:05 UTC, cleobnvntra commented on src/toml_parser/index.ts
> + * @param config - The TOML configuration.
Fixed.

2024-10-01 23:15 UTC, cleobnvntra commented on src/toml_parser/index.ts
> +    const configFile = path.resolve('.options.toml');
Done.

2024-10-01 23:42 UTC, cleobnvntra commented on src/args/flag_handlers/output.ts
> +  const outputFiles: string[] = outputConfig || []; // Initialize as an empty array
Fixed.

Now overwrites the `outputFiles` array if an output filename is provided through command line argument.

2024-10-02 00:37 UTC, Mounayer requested changes
praise: LGTM!!! This is looking very nicely well done! I just had one more minor suggestion for user experience improvement and then it's good to go!

Also, the newly added `feature` should be mentioned in `README.md`!

2024-10-02 00:37 UTC, Mounayer commented on src/toml_parser/index.ts
> +    console.error(`${err}`);
Suggestion: This is excellent, I would just make the error message better, i.e:

```typescript
console.error(`Could not parse TOML config file: `, err);
```

2024-10-02 00:38 UTC, Mounayer commented on src/toml_parser/index.ts
> +    const configFile = path.resolve('.options.toml');
This is looking great, but could the file be called `.optimizeit-config.toml` instead? Just because `options` is very general

2024-10-03 15:44 UTC, cleobnvntra commented on src/toml_parser/index.ts
> +    console.error(`${err}`);
I would have added a custom message however, the current error message thrown is already like this:

```
Error: Invalid TOML document: invalid value

1:  # output = ["test23.cpp", "test24.cpp", "test25.cpp", "test26.cpp", "test27.cpp"]
2:  break = asd
            ^
```

The error message will become:
```
Could not parse TOML config file: Error: Invalid TOML document: invalid value

1:  # output = ["test23.cpp", "test24.cpp", "test25.cpp", "test26.cpp", "test27.cpp"]
2:  break = asd
            ^
```

I can do it if you still prefer it this way.

2024-10-03 15:58 UTC, Mounayer commented on src/toml_parser/index.ts
> +    console.error(`${err}`);
Oh okay, no that's great, you can keep it as it is, although maybe we can remove the `break` line in the `toml` config, I think that might confuse them

2024-10-03 17:05 UTC, Mounayer approved these changes
praise: LGTM!!! Looks great!

2024-10-03 17:06 UTC, merged